#spring.profiles.active=devo
#spring.devtools.add-properties=false

server.port = 8091

spring.application.name= authorization-service

spring.datasource.driver-class-name=org.postgresql.Driver

# This will create/update table automatically in your database
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.show-sql=true

